/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 		*/
/*  Created On : 28-okt-2022 10:56:35 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

DROP SEQUENCE IF EXISTS "isik_isik_id_seq"
;

DROP SEQUENCE IF EXISTS "tootaja_isik_id_seq"
;

DROP SEQUENCE IF EXISTS "klient_isik_id_seq"
;

DROP SEQUENCE IF EXISTS "tootaja_rolli_omamine_tootaja_rolli_omamine_id_seq"
;

/* Drop Tables */

DROP TABLE IF EXISTS "Riik" CASCADE
;

DROP TABLE IF EXISTS "Tootaja_roll" CASCADE
;

DROP TABLE IF EXISTS "Tootaja_seisundi_liik" CASCADE
;

DROP TABLE IF EXISTS "Laadimispunkti_seisundi_liik" CASCADE
;

DROP TABLE IF EXISTS "Laadimispunkti_kategooria_tyyp" CASCADE
;

DROP TABLE IF EXISTS "Kliendi_seisundi_liik" CASCADE
;

DROP TABLE IF EXISTS "Isiku_seisundi_liik" CASCADE
;

DROP TABLE IF EXISTS "Laadimispunkti_tyyp" CASCADE
;

DROP TABLE IF EXISTS "Laadimispunkti_kategooria" CASCADE
;

DROP TABLE IF EXISTS "Isik" CASCADE
;

DROP TABLE IF EXISTS "Kasutajakonto" CASCADE
;

DROP TABLE IF EXISTS "Tootaja" CASCADE
;

DROP TABLE IF EXISTS "Laadimispunkt" CASCADE
;

DROP TABLE IF EXISTS "Klient" CASCADE
;

DROP TABLE IF EXISTS "Laadimispunkti_kategooria_omamine" CASCADE
;

DROP TABLE IF EXISTS "Tootaja_rolli_omamine" CASCADE
;

/* Create Tables */

CREATE TABLE "Riik"
(
	"riik_kood" varchar(3)	 NOT NULL,
	"riik_nimetus" varchar(60)	 NOT NULL,
	CONSTRAINT "PK_Riik" PRIMARY KEY ("riik_kood"),
	CONSTRAINT "AK_riik_nimetus" UNIQUE ("riik_nimetus"),
	CONSTRAINT "CHK_Riik_kood_on_oige" CHECK (riik_kood ~ '[A-Z]{3}'),
	CONSTRAINT "CHK_Riik_riik_nimetus_ei_ole_tyhi" CHECK (riik_nimetus !~ '^[[:space:]]*$')
)
;

CREATE TABLE "Tootaja_roll"
(
	"tootaja_roll_kood" smallint NOT NULL,
	"kirjeldus" text NULL,
	"tootaja_roll_nimetus" varchar(50)	 NOT NULL,
	CONSTRAINT "PK_Tootaja_roll" PRIMARY KEY ("tootaja_roll_kood"),
	CONSTRAINT "AK_Tootaja_roll_tootaja_roll_nimetus" UNIQUE ("tootaja_roll_nimetus"),
	CONSTRAINT "CHK_Tootaja_roll_kirjeldus_ei_tohi_olla_tyhi" CHECK (kirjeldus !~ '^[[:space:]]*$'),
	CONSTRAINT "CHK_Tootaja_roll_nimetus_ei_tohi_olla_tyhi" CHECK (tootaja_roll_nimetus !~ '^[[:space:]]*$')
)
;

CREATE TABLE "Tootaja_seisundi_liik"
(
	"tootaja_seisundi_liik_kood" smallint NOT NULL,
	"tootaja_seisundi_liik_nimetus" varchar(50)	 NOT NULL,
	CONSTRAINT "PK_Tootaja_seisundi_liik" PRIMARY KEY ("tootaja_seisundi_liik_kood"),
	CONSTRAINT "AK_Tootaja_seisundi_liik_nimetus" UNIQUE ("tootaja_seisundi_liik_nimetus"),
	CONSTRAINT "CHK_Tootaja_seisundi_liik_nimetus_ei_tohi_olla_tyhi" CHECK (tootaja_seisundi_liik_nimetus !~ '^[[:space:]]*$')
)
;

CREATE TABLE "Laadimispunkti_seisundi_liik"
(
	"laadimispunkti_seisundi_liik_kood" smallint NOT NULL,
	"laadimispunkti_seisundi_liik_nimetus" varchar(50)	 NOT NULL,
	CONSTRAINT "PK_Laadimispunkti_seisundi_liik" PRIMARY KEY ("laadimispunkti_seisundi_liik_kood"),
	CONSTRAINT "AK_laadimispunkti_seisundi_liik_nimetus" UNIQUE ("laadimispunkti_seisundi_liik_nimetus"),
	CONSTRAINT "CHK_Laadimispunkti_seisundi_liik_nimetus_ei_tohi_olla_tyhi" CHECK (laadimispunkti_seisundi_liik_nimetus !~ '^[[:space:]]*$')
)
;

CREATE TABLE "Laadimispunkti_kategooria_tyyp"
(
	"laadimispunkti_kategooria_tyyp_kood" smallint NOT NULL,
	"laadimispunkti_kategooria_tyyp_nimetus" varchar(50)	 NOT NULL,
	CONSTRAINT "PK_Laadimispunkti_kategooria_tyyp" PRIMARY KEY ("laadimispunkti_kategooria_tyyp_kood"),
	CONSTRAINT "AK_Laadimispunkti_kategooria_tyyp_nimetus" UNIQUE ("laadimispunkti_kategooria_tyyp_nimetus"),
	CONSTRAINT "CHK_Laadimispunkti_kategooria_tyyp_nimetus_ei_tohi_olla_tyhi" CHECK (laadimispunkti_kategooria_tyyp_nimetus !~ '^[[:space:]]*$')
)
;

CREATE TABLE "Kliendi_seisundi_liik"
(
	"kliendi_seisundi_liik_kood" smallint NOT NULL,
	"kliendi_seisundi_liik_nimetus" varchar(50)	 NOT NULL,
	CONSTRAINT "PK_Kliendi_seisundi_liik" PRIMARY KEY ("kliendi_seisundi_liik_kood"),
	CONSTRAINT "AK_Kliendi_seisundi_liik_nimetus" UNIQUE ("kliendi_seisundi_liik_nimetus"),
	CONSTRAINT "CHK_Kliendi_seisundi_liik_nimetus_ei_tohi_olla_tyhi" CHECK (kliendi_seisundi_liik_nimetus !~ '^[[:space:]]*$')
)
;

CREATE TABLE "Isiku_seisundi_liik"
(
	"isiku_seisundi_liik_kood" smallint NOT NULL,
	"isiku_seisundi_liik_nimetus" varchar(50)	 NOT NULL,
	CONSTRAINT "PK_Isiku_seisundi_liik" PRIMARY KEY ("isiku_seisundi_liik_kood"),
	CONSTRAINT "AK_Isiku_seisundi_liik_nimetus" UNIQUE ("isiku_seisundi_liik_nimetus"),
	CONSTRAINT "CHK_Isiku_seisundi_liik_nimetus_ei_tohi_olla_tyhi" CHECK (isiku_seisundi_liik_nimetus !~ '^[[:space:]]*$')
)
;

CREATE TABLE "Laadimispunkti_tyyp"
(
	"laadimispunkti_tyyp_kood" smallint NOT NULL,
	kWh smallint NOT NULL,
	"nimetus" varchar(50)	 NOT NULL,
	CONSTRAINT "PK_Laadimispunkti_tyyp" PRIMARY KEY ("laadimispunkti_tyyp_kood"),
	CONSTRAINT "AK_Laadimispunkti_tyyp_kWh" UNIQUE (kWh),
	CONSTRAINT "CHK_Laadimispunkti_tyyp_kWh_on_oige_kogus" CHECK (kWh BETWEEN 0 AND 200),
	CONSTRAINT "CHK_Laadimispunkti_tyyp_nimetus_ei_ole_tyhi" CHECK (nimetus !~ '^[[:space:]]*$')
)
;

CREATE TABLE "Laadimispunkti_kategooria"
(
	"laadimispunkti_kategooria_kood" smallint NOT NULL,
	"laadimispunkti_kategooria_nimetus" varchar(50)	 NOT NULL,
	"laadimispunkti_kategooria_tyyp_kood" smallint NOT NULL,
	CONSTRAINT "PK_Laadimispunkti_kategooria" PRIMARY KEY ("laadimispunkti_kategooria_kood"),
	CONSTRAINT "AK_Laadimispunkti_kategooria_kood_nimetus" UNIQUE ("laadimispunkti_kategooria_tyyp_kood","laadimispunkti_kategooria_nimetus"),
	CONSTRAINT "CHK_Laadimispunkti_kategooria_nimetus_ei_tohi_olla_tyhi" CHECK (laadimispunkti_kategooria_nimetus !~ '^[[:space:]]*$'),
	CONSTRAINT "FK_Laadimispunkti_kategooria_tyyp_kood" FOREIGN KEY ("laadimispunkti_kategooria_tyyp_kood") REFERENCES "Laadimispunkti_kategooria_tyyp" ("laadimispunkti_kategooria_tyyp_kood") ON DELETE No Action ON UPDATE Cascade
)
;

CREATE TABLE "Isik"
(
	"isik_id" bigserial NOT NULL DEFAULT nextval(('"isik_isik_id_seq"'::text)::regclass),
	"isikukood" varchar(255)	 NOT NULL,
	"synni_kp" date NOT NULL,
	"reg_aeg" time without time zone NOT NULL DEFAULT LOCALTIMESTAMP(0),
	"eesnimi" varchar(50)	 NULL,
	"perenimi" varchar(50)	 NULL,
	"elukoht" varchar(1024)	 NULL,
	"e_meil" varchar(254)	 NOT NULL,
	"riik_kood" varchar(3)	 NOT NULL,
	"isiku_seisundi_liik_kood" smallint NOT NULL DEFAULT 0,
	CONSTRAINT "PK_Isik" PRIMARY KEY ("isik_id"),
	CONSTRAINT "AK_Isik_id_riik" UNIQUE ("isikukood","riik_kood"),
	CONSTRAINT "CHK_Isik_eesnimi_not_null" CHECK (eesnimi IS NOT NULL),
	CONSTRAINT "CHK_Isik_email_oigsus" CHECK (e_meil ~* '^[a-z0-9._%-]+@[a-z0-9.-]+[.][a-z]+$'),
	CONSTRAINT "CHK_Isik_eesnimi_oigsus" CHECK (perenimi !~ '^[[:space:]]*$'),
	CONSTRAINT "CHK_Isik_synni_kp_oige_vahemik" CHECK (synni_kp BETWEEN To_DATE('01-01-1900', 'DD-MM-YYYY') AND To_DATE('31-12-2100', 'DD-MM-YYYY')),
	CONSTRAINT "CHK_Isik_synnikp_ei_ole_suurem_reg_ajast" CHECK (reg_aeg::date >= synni_kp),
	CONSTRAINT "CHK_Isik_elukoht_ei_tohi_olla_tyhi" CHECK (elukoht !~ '^[[:space:]]*$'),
	CONSTRAINT "CHK_Isik_isikukood_oigsus" CHECK (isikukood !~ '^[[:space:]]*$' AND isikukood ~ '^[[:alnum:] /+=-]+$'),
	CONSTRAINT "CHK_Isik_perenimi_not_null" CHECK (perenimi IS NOT NULL),
	CONSTRAINT "CHK_Isik_perenimi_oigsus" CHECK (eesnimi !~ '^[[:space:]]*$'),
	CONSTRAINT "CHK_Isik_elukoht_ei_tohi_olla_ainult_numbrid" CHECK (elukoht !~ '^[0-9]+$'),
	CONSTRAINT "FK_Isik_Isiku_seisundi_liik" FOREIGN KEY ("isiku_seisundi_liik_kood") REFERENCES "Isiku_seisundi_liik" ("isiku_seisundi_liik_kood") ON DELETE No Action ON UPDATE Cascade,
	CONSTRAINT "FK_Isik_isikukoodi_riik" FOREIGN KEY ("riik_kood") REFERENCES "Riik" ("riik_kood") ON DELETE No Action ON UPDATE Cascade
)
;

CREATE TABLE "Kasutajakonto"
(
	"isik_id" bigint NOT NULL,
	"parool" varchar(50)	 NOT NULL,
	"on_aktiivne" boolean NOT NULL DEFAULT TRUE,
	CONSTRAINT "PK_Kasutajakonto" PRIMARY KEY ("isik_id"),
	CONSTRAINT "CHK_Kasutajakonto_parool_ei_ole_tyhi" CHECK (parool !~ '^[[:space:]]*$'),
	CONSTRAINT "FK_Kasutajakonto_Isik" FOREIGN KEY ("isik_id") REFERENCES "Isik" ("isik_id") ON DELETE Cascade ON UPDATE No Action
)
;

CREATE TABLE "Tootaja"
(
	"isik_id" bigserial NOT NULL DEFAULT nextval(('"tootaja_isik_id_seq"'::text)::regclass),
	"tootaja_seisundi_liik_kood" smallint NOT NULL DEFAULT 0,
	"Mentor" bigint NULL,
	CONSTRAINT "PK_Tootaja" PRIMARY KEY ("isik_id"),
	CONSTRAINT "CHK_Tootaja_isik_ja_mentor_ei_ole_samad" CHECK (isik_id <> mentor),
	CONSTRAINT "FK_Tootaja_Tootaja_seisundi_liik" FOREIGN KEY ("tootaja_seisundi_liik_kood") REFERENCES "Tootaja_seisundi_liik" ("tootaja_seisundi_liik_kood") ON DELETE No Action ON UPDATE Cascade,
	CONSTRAINT "FK_Tootaja_Isik" FOREIGN KEY ("isik_id") REFERENCES "Isik" ("isik_id") ON DELETE Cascade ON UPDATE No Action,
	CONSTRAINT "FK_Tootaja_Mentor" FOREIGN KEY ("Mentor") REFERENCES "Tootaja" ("isik_id") ON DELETE Set Null ON UPDATE No Action
)
;

CREATE TABLE "Laadimispunkt"
(
	"laadimispunkti_kood" bigint NOT NULL,
	"laiuskraad" decimal(7,4) NOT NULL,
	"pikkuskraad" decimal(6,4) NOT NULL,
	"laadimispunkti_nimetus" varchar(50)	 NOT NULL,
	"reg_aeg" timestamp without time zone NOT NULL DEFAULT LOCALTIMESTAMP(0),
	"registreerija_id" bigint NOT NULL,
	"laadimispunkti_seisundi_liik_kood" smallint NOT NULL DEFAULT 0,
	"laadimispunkti_tyyp_kood" smallint NOT NULL,
	CONSTRAINT "PK_Laadimispunkt" PRIMARY KEY ("laadimispunkti_kood"),
	CONSTRAINT "AK_Laadimispunkt_laadimimispunkti_nimi" UNIQUE ("laadimispunkti_nimetus"),
	CONSTRAINT "CHK_kehtiv_laiuskraad" CHECK (laiuskraad BETWEEN -180 AND 180),
	CONSTRAINT "CHK_kehtiv_pikkuskraad" CHECK (pikkuskraad BETWEEN -90 AND 90),
	CONSTRAINT "CHK_nimetus_ei_ole_tyhi_string" CHECK (laadimispunkti_nimetus !~ '^[[:space:]]*$'),
	CONSTRAINT "CHK_reg_aeg_oiges_vahemikus" CHECK (reg_aeg BETWEEN To_Timestamp('01-01-2010 00:00:00', 'DD-MM-YYYY HH24:MI:SS') AND To_Timestamp('31.12.2100 23:59:59', 'DD-MM-YYYY HH24:MI:SS')),
	CONSTRAINT "FK_Laadimispunkt_Laadimispunkti_seisundi_liik_kood" FOREIGN KEY ("laadimispunkti_seisundi_liik_kood") REFERENCES "Laadimispunkti_seisundi_liik" ("laadimispunkti_seisundi_liik_kood") ON DELETE No Action ON UPDATE Cascade,
	CONSTRAINT "FK_Laadimispunkt_registreerija_id" FOREIGN KEY ("registreerija_id") REFERENCES "Tootaja" ("isik_id") ON DELETE No Action ON UPDATE No Action,
	CONSTRAINT "FK_Laadimispunkt_Laadimispunkti_tyyp" FOREIGN KEY ("laadimispunkti_tyyp_kood") REFERENCES "Laadimispunkti_tyyp" ("laadimispunkti_tyyp_kood") ON DELETE No Action ON UPDATE Cascade
)
;

CREATE TABLE "Klient"
(
	"isik_id" bigserial NOT NULL DEFAULT nextval(('"klient_isik_id_seq"'::text)::regclass),
	"on_nous_tylitamisega" boolean NOT NULL DEFAULT FALSE,
	"kliendi_seisundi_liik_kood" smallint NOT NULL DEFAULT 0,
	CONSTRAINT "PK_Klient" PRIMARY KEY ("isik_id"),
	CONSTRAINT "FK_Klient_Kliendi_seisundi_liik" FOREIGN KEY ("kliendi_seisundi_liik_kood") REFERENCES "Kliendi_seisundi_liik" ("kliendi_seisundi_liik_kood") ON DELETE No Action ON UPDATE Cascade,
	CONSTRAINT "FK_Klient_Isik" FOREIGN KEY ("isik_id") REFERENCES "Isik" ("isik_id") ON DELETE Cascade ON UPDATE No Action
)
;

CREATE TABLE "Laadimispunkti_kategooria_omamine"
(
	"laadimispunkti_kood" bigint NOT NULL,
	"laadimispunkti_kategooria_kood" smallint NOT NULL,
	CONSTRAINT "PK_Laadimispunkti_kategooria_omamine" PRIMARY KEY ("laadimispunkti_kood","laadimispunkti_kategooria_kood"),
	CONSTRAINT "FK_LP_K_omamine_LP_K_kood" FOREIGN KEY ("laadimispunkti_kategooria_kood") REFERENCES "Laadimispunkti_kategooria" ("laadimispunkti_kategooria_kood") ON DELETE No Action ON UPDATE Cascade,
	CONSTRAINT "FK_LP_K_omamine_LP_kood" FOREIGN KEY ("laadimispunkti_kood") REFERENCES "Laadimispunkt" ("laadimispunkti_kood") ON DELETE No Action ON UPDATE Cascade
)
;

CREATE TABLE "Tootaja_rolli_omamine"
(
	"tootaja_rolli_omamine_id" bigserial NOT NULL DEFAULT nextval(('"tootaja_rolli_omamine_tootaja_rolli_omamine_id_seq"'::text)::regclass),
	"alguse_aeg" timestamp without time zone NOT NULL DEFAULT LOCALTIMESTAMP(0),
	"lopu_aeg" timestamp without time zone NOT NULL DEFAULT 'infinity',
	"tootaja_roll_kood" smallint NOT NULL,
	"isik_id" bigint NOT NULL,
	CONSTRAINT "PK_Tootaja_rolli_omamine_id" PRIMARY KEY ("tootaja_rolli_omamine_id"),
	CONSTRAINT "AK_Tootaja_rolli_omamine_ei_saa_sama_algatada" UNIQUE ("isik_id","alguse_aeg","tootaja_roll_kood"),
	CONSTRAINT "CHK_Tootaja_rolli_omamine_lopp_on_suurem_algusest" CHECK (lopu_aeg > alguse_aeg),
	CONSTRAINT "CHK_Tootaja_rolli_omamine_alguse_aeg_oiges_vahemikus" CHECK (alguse_aeg BETWEEN To_DATE('01-01-2010', 'DD-MM-YYYY') AND To_DATE('31-12-2100', 'DD-MM-YYYY')),
	CONSTRAINT "CHK_Tootaja_rolli_omamine_lopu_aeg_oiges_vahemikus" CHECK (lopu_aeg BETWEEN To_DATE('01-01-2010', 'DD-MM-YYYY') AND To_DATE('31-12-2100', 'DD-MM-YYYY')),
	CONSTRAINT "FK_Tootaja_rolli_omamine_Tootaja_roll" FOREIGN KEY ("tootaja_roll_kood") REFERENCES "Tootaja_roll" ("tootaja_roll_kood") ON DELETE No Action ON UPDATE Cascade,
	CONSTRAINT "FK_Tootaja_rolli_omamine_Tootaja" FOREIGN KEY ("isik_id") REFERENCES "Tootaja" ("isik_id") ON DELETE Cascade ON UPDATE No Action
)
;

/* Create Table Comments, Sequences for Autonumber Columns */

CREATE SEQUENCE "isik_isik_id_seq" INCREMENT 1 START 1
;

CREATE SEQUENCE "tootaja_isik_id_seq" INCREMENT 1 START 1
;

COMMENT ON TABLE "Laadimispunkt"
	IS 'Vaja nimetusele panna unique kitsendus.  ? Kas on vaja lisada klassifikaatorit ?  Kuidas seada attribuut kohustuslikuks??????????!?!?!?!?!?!?!?!?!'
;

CREATE SEQUENCE "klient_isik_id_seq" INCREMENT 1 START 1
;

CREATE SEQUENCE "tootaja_rolli_omamine_tootaja_rolli_omamine_id_seq" INCREMENT 1 START 1
;

/* Create Primary Keys, Indexes, Uniques, Checks */

CREATE INDEX "IXFK_Laadimispunkti_tyyp_kWh" ON "Laadimispunkti_tyyp" ("kWh" ASC)
;

CREATE INDEX "IXFK_Laadimispunkti_kategooria_Laadimispunkti_kategooria_tyyp" ON "Laadimispunkti_kategooria" ("laadimispunkti_kategooria_tyyp_kood" ASC)
;

CREATE INDEX "IXFK_Isik_isikukoodi_riik" ON "Isik" ("riik_kood" ASC)
;

CREATE INDEX "IXFK_Isik_Isiku_seisundi_liik" ON "Isik" ("isiku_seisundi_liik_kood" ASC)
;

CREATE INDEX "IXFK_Kasutajakonto_Isik" ON "Kasutajakonto" ("isik_id" ASC)
;

CREATE INDEX "IXFK_Tootaja_Isik" ON "Tootaja" ("isik_id" ASC)
;

CREATE INDEX "IXFK_Tootaja_Mentor" ON "Tootaja" ("Mentor" ASC)
;

CREATE INDEX "IXFK_Tootaja_Tootaja_seisundi_liik" ON "Tootaja" ("tootaja_seisundi_liik_kood" ASC)
;

CREATE INDEX "IXFK_Laadimispunkt_Laadimispunkti_seisundi_liik" ON "Laadimispunkt" ("laadimispunkti_seisundi_liik_kood" ASC)
;

CREATE INDEX "IXFK_Laadimispunkt_Laadimispunkti_tyyp" ON "Laadimispunkt" ("laadimispunkti_tyyp_kood" ASC)
;

CREATE INDEX "IXFK_Laadimispunkt_registreerija_id" ON "Laadimispunkt" ("registreerija_id" ASC)
;

CREATE INDEX "IXFK_Klient_Isik" ON "Klient" ("isik_id" ASC)
;

CREATE INDEX "IXFK_Klient_Kliendi_seisundi_liik" ON "Klient" ("kliendi_seisundi_liik_kood" ASC)
;

CREATE INDEX "IXFK_LP_K_omamine_LP_K_kood" ON "Laadimispunkti_kategooria_omamine" ("laadimispunkti_kategooria_kood" ASC)
;

CREATE INDEX "IXFK_LP_K_omamine_LP_kood" ON "Laadimispunkti_kategooria_omamine" ("laadimispunkti_kood" ASC)
;

CREATE INDEX "IXFK_Tootaja_rolli_omamine_Tootaja" ON "Tootaja_rolli_omamine" ("isik_id" ASC)
;

CREATE INDEX "IXFK_Tootaja_rolli_omamine_Tootaja_roll" ON "Tootaja_rolli_omamine" ("tootaja_roll_kood" ASC)
;
